server:
  port: 8080 
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/rookie
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    favicon:
      enabled: false
  data:
    neo4j:
      username: neo4j
      password: K787s84m
    mongodb:
      username: mongodb
      password: mongodb
      host: localhost
      port: 27017
      database: test
#      uri: mongodb://user:password@localhost/test
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE